server:
  port: 18762
  connection-timeout: 1000ms
  compression:
    enabled: true
  tomcat:
    max-threads: 100
    max-connections: 10
    min-spare-threads: 5
    uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        http-only: true
        domain: /

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: spring-cloud-client
  devtools:
    restart:
      enabled: false
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true

#服务注册中心配置
#eureka:
#  instance:
#    #心跳间隔
#    lease-renewal-interval-in-seconds: 5
#    #没有心跳的淘汰时间
#    lease-expiration-duration-in-seconds: 10
#    prefer-ip-address: true
#  client:
#    #定时刷新本地缓存时间
#    registry-fetch-interval-seconds: 3
#    instance-info-replication-interval-seconds: 3
#    service-url:
#      defaultZone:  http://localhost:18761/eureka/

# feign : 使用okHttp做为http client, 读写
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 100000
  compression:
    request:
      enabled: true
    response:
      enabled: true
#  hystrix:
#    enabled: false

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000

ribbon:
  ServerListRefreshInterval: 2000
  ReadTimeout: 10000
  ConnectTimeout: 10000
  OkToRetryOnAllOperations: true

#程序管理endpoint
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

api:
  server:
    host: http://localhost:18764